version: '3.9'

services:
  nextjs:
    container_name: authguard_docs
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3777:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/app